# Generated by Django 3.0.5 on 2020-04-13 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='price',
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='designer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='year',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Wearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Worn')),
                ('wear', models.CharField(choices=[('D', 'Daily'), ('B', 'Beaters'), ('S', 'Special Event')], default='D', max_length=10)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sneaker')),
            ],
        ),
        migrations.AddField(
            model_name='sneaker',
            name='boxes',
            field=models.ManyToManyField(to='main_app.Box'),
        ),
    ]
