# Generated by Django 3.0.5 on 2020-04-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Restoration Date')),
                ('restore', models.CharField(choices=[('0', 'None'), ('1', 'Once'), ('2+', 'Multiple')], default=('0', 'None'), max_length=2)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sneaker')),
            ],
        ),
    ]
