# Generated by Django 3.0.5 on 2020-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200410_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='boxes',
            field=models.ManyToManyField(to='main_app.Box'),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='wear',
            field=models.CharField(choices=[('D', 'Daily'), ('B', 'Beaters'), ('S', 'Special Event')], default='D', max_length=1),
        ),
    ]
