# Generated by Django 3.0.5 on 2020-04-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200411_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='designer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='year',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='wear',
            field=models.CharField(choices=[('D', 'Daily'), ('B', 'Beaters'), ('S', 'Special Event')], default='D', max_length=3),
        ),
    ]
