# Generated by Django 3.0.5 on 2020-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200411_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
