# Generated by Django 3.0.5 on 2020-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200412_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='designer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
